apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/lijcam/ADOAROATO-infra
    targetRevision: main
    path: app
  destination:
    #REPLACE WITH CLUSTER NAME
    server: https://api.anvv4n4h.australiacentral.aroapp.io:6443
    namespace: web-app
